services:
  twiistsync:
    build: .
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /mnt/user/Docker/twiistsync/config:/config:ro
      - /mnt/user/Docker/twiistsync/data:/data
